export enum TopupStatusEnum {
	PENDING = 'PENDING',
	SUCCESS = 'SUCCESS',
	FAILED = 'FAILED',
	EXPIRED = 'EXPIRED'
}

export enum PaymentStatusEnum {
	CAPTURE = 'CAPTURE',
	SETTLEMENT = 'SETTLEMENT',
	PENDING = 'PENDING',
	DENY = 'DENY',
	CANCEL = 'CANCEL',
	EXPIRE = 'EXPIRE',
	FAILURE = 'FAILURE',
	REFUND = 'REFUND',
	PARTIAL_REFUND = 'PARTIAL_REFUND',
	AUTHORIZE = 'AUTHORIZE'
}
